/**
 * Private object storage for media blobs (selfies, branding) — PRD §12/§14,
 * decisions.md #5/#6.
 *
 * STORAGE LAYOUT (filesystem volume for the MVP):
 *
 *   STORAGE_DIR (env, default ./data/objects — git-ignored, docker-ignored,
 *   OUTSIDE the Next.js public web root)
 *     └── <kind>/                     e.g. "selfie/"
 *         └── <object UUID>.jpg       opaque, unguessable filename
 *
 * The DB row (`stored_objects`, migration 0006) is the metadata of record:
 * id, tenant_id, kind, relative_path (UNIQUE), media_type, byte_size,
 * sha256. The file on disk is addressed ONLY by the DB's relative_path —
 * never by a client-supplied path — and is served through an authorized
 * endpoint (Task 7), never as a static asset.
 *
 * SECURITY BOUNDARY: every path resolved by this module is constrained to
 * STORAGE_DIR; `..`, absolute paths, and non-UUID object ids are rejected
 * before touching the filesystem (path traversal defense).
 */

import { createHash, randomUUID } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { Queryable } from '../db/queryable.ts';

const EXTENSION_BY_MEDIA_TYPE: Record<string, string> = {
  'image/jpeg': '.jpg',
  'image/png': '.png',
  'image/webp': '.webp',
};

/** Object ids are UUIDs generated by this module; anything else is hostile input. */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

/** A kind becomes a single path segment under the storage root. */
const KIND_RE = /^[a-z][a-z0-9_]*$/;

/** Resolves the storage root: explicit arg > STORAGE_DIR env > ./data/objects. */
export function resolveStorageDir(storageDir?: string): string {
  return path.resolve(storageDir ?? process.env.STORAGE_DIR ?? './data/objects');
}

/**
 * Resolves a DB relative_path to an absolute path inside `storageDir`.
 * Throws when the path would escape the storage root (path traversal).
 */
export function getObjectPath(relativePath: string, storageDir?: string): string {
  if (typeof relativePath !== 'string' || relativePath.length === 0) {
    throw new Error('invalid object path: empty');
  }
  if (path.isAbsolute(relativePath)) {
    throw new Error(`invalid object path (absolute path rejected): ${relativePath}`);
  }

  const root = resolveStorageDir(storageDir);
  const resolved = path.resolve(root, relativePath);
  if (resolved !== root && !resolved.startsWith(root + path.sep)) {
    throw new Error(`invalid object path (path traversal outside storage root rejected): ${relativePath}`);
  }
  return resolved;
}

export interface StoreObjectArgs {
  tenantId: string;
  /** Object kind, e.g. 'selfie', 'branding_logo'. Becomes the subdirectory. */
  kind: string;
  buffer: Buffer;
  mediaType: string;
  /** Overrides the storage root (tests); defaults to STORAGE_DIR env / ./data/objects. */
  storageDir?: string;
}

export interface StoredObjectRef {
  id: string;
  relativePath: string;
}

/**
 * Stores `buffer` under an opaque UUID filename and records the metadata row
 * in `stored_objects`. Returns { id, relativePath }; the id is safe to hand
 * to the attendance event transaction as `selfieObjectId`.
 *
 * The row is inserted via `client`, so callers can run this inside their own
 * transaction if the object write must roll back with other work.
 */
export async function storeObject(client: Queryable, args: StoreObjectArgs): Promise<StoredObjectRef> {
  if (!KIND_RE.test(args.kind)) {
    throw new Error(`invalid object kind: ${args.kind}`);
  }
  if (!UUID_RE.test(args.tenantId)) {
    throw new Error(`invalid tenant id: ${args.tenantId}`);
  }

  const id = randomUUID();
  const extension = EXTENSION_BY_MEDIA_TYPE[args.mediaType] ?? '.bin';
  const relativePath = `${args.kind}/${id}${extension}`;
  const absolutePath = getObjectPath(relativePath, args.storageDir);

  // Write the bytes first so a failed insert never leaves an orphan row.
  // The blob is data, never executable content (PRD §14): it lives outside
  // the web root and is only ever streamed back by an authorized endpoint.
  await fs.mkdir(path.dirname(absolutePath), { recursive: true });
  await fs.writeFile(absolutePath, args.buffer);

  const sha256 = createHash('sha256').update(args.buffer).digest('hex');
  await client.query(
    `INSERT INTO stored_objects (id, tenant_id, kind, relative_path, media_type, byte_size, sha256)
     VALUES ($1, $2, $3, $4, $5, $6, $7)`,
    [id, args.tenantId, args.kind, relativePath, args.mediaType, args.buffer.length, sha256],
  );

  return { id, relativePath };
}

export interface ReadObjectArgs {
  tenantId: string;
  id: string;
  storageDir?: string;
}

export interface ReadObjectResult {
  buffer: Buffer;
  mediaType: string;
}

/**
 * Reads back a stored object, scoped to `tenantId` (an object belonging to
 * another tenant is indistinguishable from a missing one). The file path
 * comes from the DB row, re-validated against the storage root.
 */
export async function readObject(client: Queryable, args: ReadObjectArgs): Promise<ReadObjectResult> {
  if (!UUID_RE.test(args.id)) {
    throw new Error('object not found');
  }
  const rows = await client.query<{ relative_path: string; media_type: string; deleted_at: Date | null }>(
    `SELECT relative_path, media_type, deleted_at FROM stored_objects WHERE id = $1 AND tenant_id = $2`,
    [args.id, args.tenantId],
  );
  const row = rows.rows[0];
  if (!row || row.deleted_at !== null) {
    throw new Error('object not found');
  }
  const absolutePath = getObjectPath(row.relative_path, args.storageDir);
  const buffer = await fs.readFile(absolutePath);
  return { buffer, mediaType: row.media_type };
}
