/**
 * Private object storage for media blobs (selfies, branding) — PRD §12/§14,
 * decisions.md #5/#6.
 *
 * STORAGE LAYOUT (filesystem volume for the MVP):
 *
 *   STORAGE_DIR (env, default ./data/objects — git-ignored, docker-ignored,
 *   OUTSIDE the Next.js public web root)
 *     └── <kind>/                     e.g. "selfie/"
 *         └── <object UUID>.jpg       opaque, unguessable filename
 *
 * The DB row (`stored_objects`, migration 0006) is the metadata of record:
 * id, tenant_id, kind, relative_path (UNIQUE), media_type, byte_size,
 * sha256. The file on disk is addressed ONLY by the DB's relative_path —
 * never by a client-supplied path — and is served through an authorized
 * endpoint (Task 7), never as a static asset.
 *
 * SECURITY BOUNDARY: every path resolved by this module is constrained to
 * STORAGE_DIR; `..`, absolute paths, and non-UUID object ids are rejected
 * before touching the filesystem (path traversal defense).
 *
 * HARDENING (code-quality review):
 *   - ATOMIC WRITES: blobs are written to a temp file in the same directory
 *     and then renamed onto the final path (atomic on the same volume), so a
 *     crash mid-write never leaves a truncated blob at the final path.
 *   - NO ORPHAN BLOBS: if the `stored_objects` INSERT fails after the file
 *     landed, the file is unlinked (best-effort) before the error propagates.
 *   - INTEGRITY ON READ: readObject recomputes the sha256 of the bytes on
 *     disk and refuses to serve them when it mismatches the stored value
 *     (bit rot / tampering is detected, not echoed back).
 *   - MEDIA-TYPE ALLOWLIST: only SERVABLE_MEDIA_TYPES may be stored, and
 *     readObject only ever returns an allowlisted Content-Type (anything
 *     else — e.g. a legacy text/html row — is served as
 *     application/octet-stream). This protects the Task 7 serving endpoint
 *     from content-sniffing/XSS via a stored HTML blob.
 */

import { createHash, randomUUID } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { Queryable } from '../db/queryable.ts';

/**
 * Media types this module will store and serve back as Content-Type.
 * Anything else is rejected on write and coerced to
 * `application/octet-stream` on read (see the module header).
 */
const SERVABLE_MEDIA_TYPES = new Set(['image/jpeg', 'image/png', 'image/webp']);

/** Safe fallback Content-Type for stored rows outside the allowlist. */
const FALLBACK_MEDIA_TYPE = 'application/octet-stream';

const EXTENSION_BY_MEDIA_TYPE: Record<string, string> = {
  'image/jpeg': '.jpg',
  'image/png': '.png',
  'image/webp': '.webp',
};

/** Object ids are UUIDs generated by this module; anything else is hostile input. */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

/** A kind becomes a single path segment under the storage root. */
const KIND_RE = /^[a-z][a-z0-9_]*$/;

/** Resolves the storage root: explicit arg > STORAGE_DIR env > ./data/objects. */
export function resolveStorageDir(storageDir?: string): string {
  return path.resolve(storageDir ?? process.env.STORAGE_DIR ?? './data/objects');
}

/**
 * Resolves a DB relative_path to an absolute path inside `storageDir`.
 * Throws when the path would escape the storage root (path traversal).
 */
export function getObjectPath(relativePath: string, storageDir?: string): string {
  if (typeof relativePath !== 'string' || relativePath.length === 0) {
    throw new Error('invalid object path: empty');
  }
  if (path.isAbsolute(relativePath)) {
    throw new Error(`invalid object path (absolute path rejected): ${relativePath}`);
  }

  const root = resolveStorageDir(storageDir);
  const resolved = path.resolve(root, relativePath);
  if (resolved !== root && !resolved.startsWith(root + path.sep)) {
    throw new Error(`invalid object path (path traversal outside storage root rejected): ${relativePath}`);
  }
  return resolved;
}

export interface StoreObjectArgs {
  tenantId: string;
  /** Object kind, e.g. 'selfie', 'branding_logo'. Becomes the subdirectory. */
  kind: string;
  buffer: Buffer;
  mediaType: string;
  /** Overrides the storage root (tests); defaults to STORAGE_DIR env / ./data/objects. */
  storageDir?: string;
}

export interface StoredObjectRef {
  id: string;
  relativePath: string;
}

/**
 * Stores `buffer` under an opaque UUID filename and records the metadata row
 * in `stored_objects`. Returns { id, relativePath }; the id is safe to hand
 * to the attendance event transaction as `selfieObjectId`.
 *
 * The row is inserted via `client`, so callers can run this inside their own
 * transaction if the object write must roll back with other work.
 */
export async function storeObject(client: Queryable, args: StoreObjectArgs): Promise<StoredObjectRef> {
  if (!KIND_RE.test(args.kind)) {
    throw new Error(`invalid object kind: ${args.kind}`);
  }
  if (!UUID_RE.test(args.tenantId)) {
    throw new Error(`invalid tenant id: ${args.tenantId}`);
  }
  if (!SERVABLE_MEDIA_TYPES.has(args.mediaType)) {
    throw new Error(`media type is not servable: ${args.mediaType}`);
  }

  const id = randomUUID();
  const extension = EXTENSION_BY_MEDIA_TYPE[args.mediaType] ?? '.bin';
  const relativePath = `${args.kind}/${id}${extension}`;
  const absolutePath = getObjectPath(relativePath, args.storageDir);

  // Write the bytes first so a failed insert never leaves an orphan row.
  // The blob is data, never executable content (PRD §14): it lives outside
  // the web root and is only ever streamed back by an authorized endpoint.
  await fs.mkdir(path.dirname(absolutePath), { recursive: true });

  // Atomic publish: write to a temp file in the SAME directory, then rename
  // (atomic on the same volume) so a crash mid-write can never leave a
  // truncated blob at the final path. The temp name is UUID-suffixed so
  // concurrent stores never collide.
  const tempPath = `${absolutePath}.${randomUUID()}.tmp`;
  try {
    await fs.writeFile(tempPath, args.buffer);
    await fs.rename(tempPath, absolutePath);
  } catch (err) {
    await fs.unlink(tempPath).catch(() => {});
    throw err;
  }

  const sha256 = createHash('sha256').update(args.buffer).digest('hex');
  try {
    await client.query(
      `INSERT INTO stored_objects (id, tenant_id, kind, relative_path, media_type, byte_size, sha256)
       VALUES ($1, $2, $3, $4, $5, $6, $7)`,
      [id, args.tenantId, args.kind, relativePath, args.mediaType, args.buffer.length, sha256],
    );
  } catch (err) {
    // The row never landed: remove the just-written blob so it cannot
    // orphan on disk, then let the original error propagate.
    await fs.unlink(absolutePath).catch(() => {});
    throw err;
  }

  return { id, relativePath };
}

export interface ReadObjectArgs {
  tenantId: string;
  id: string;
  storageDir?: string;
}

export interface ReadObjectResult {
  buffer: Buffer;
  mediaType: string;
}

/**
 * Reads back a stored object, scoped to `tenantId` (an object belonging to
 * another tenant is indistinguishable from a missing one). The file path
 * comes from the DB row, re-validated against the storage root.
 *
 * The sha256 recorded at store time is recomputed over the bytes on disk; a
 * mismatch means the blob was corrupted or tampered with after the fact and
 * throws instead of serving bad bytes. The returned media type is always
 * allowlisted (legacy rows fall back to application/octet-stream) so the
 * Task 7 serving endpoint can use it directly as Content-Type.
 */
export async function readObject(client: Queryable, args: ReadObjectArgs): Promise<ReadObjectResult> {
  if (!UUID_RE.test(args.id)) {
    throw new Error('object not found');
  }
  const rows = await client.query<{ relative_path: string; media_type: string; sha256: string; deleted_at: Date | null }>(
    `SELECT relative_path, media_type, sha256, deleted_at FROM stored_objects WHERE id = $1 AND tenant_id = $2`,
    [args.id, args.tenantId],
  );
  const row = rows.rows[0];
  if (!row || row.deleted_at !== null) {
    throw new Error('object not found');
  }
  const absolutePath = getObjectPath(row.relative_path, args.storageDir);
  const buffer = await fs.readFile(absolutePath);
  const actualSha256 = createHash('sha256').update(buffer).digest('hex');
  if (actualSha256 !== row.sha256) {
    throw new Error(`object failed integrity check (sha256 mismatch): ${args.id}`);
  }
  const mediaType = SERVABLE_MEDIA_TYPES.has(row.media_type) ? row.media_type : FALLBACK_MEDIA_TYPE;
  return { buffer, mediaType };
}
